services:
  - type: web
    name: your-project-name
    env: node
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString 